/**
 * OS-consistent font lists.
 * Each entry: font name → list of OS IDs where it exists.
 * Used to generate a realistic font fingerprint matching the profile OS.
 */

const FONT_DATABASE = {
  // === WINDOWS 10/11 ===
  'Arial': ['windows'],
  'Arial Black': ['windows'],
  'Arial Narrow': ['windows'],
  'Bahnschrift': ['windows'],
  'Calibri': ['windows'],
  'Cambria': ['windows'],
  'Cambria Math': ['windows'],
  'Candara': ['windows'],
  'Comic Sans MS': ['windows'],
  'Consolas': ['windows'],
  'Constantia': ['windows'],
  'Corbel': ['windows'],
  'Courier New': ['windows'],
  'Ebrima': ['windows'],
  'Franklin Gothic Medium': ['windows'],
  'Gabriola': ['windows'],
  'Gadugi': ['windows'],
  'Georgia': ['windows'],
  'HoloLens MDL2 Assets': ['windows'],
  'Impact': ['windows'],
  'Ink Free': ['windows'],
  'Javanese Text': ['windows'],
  'Leelawadee UI': ['windows'],
  'Lucida Console': ['windows'],
  'Lucida Sans Unicode': ['windows'],
  'Malgun Gothic': ['windows'],
  'Marlett': ['windows'],
  'Microsoft Himalaya': ['windows'],
  'Microsoft JhengHei': ['windows'],
  'Microsoft New Tai Lue': ['windows'],
  'Microsoft PhagsPa': ['windows'],
  'Microsoft Sans Serif': ['windows'],
  'Microsoft Tai Le': ['windows'],
  'Microsoft YaHei': ['windows'],
  'Microsoft YaHei UI': ['windows'],
  'Microsoft Yi Baiti': ['windows'],
  'MingLiU-ExtB': ['windows'],
  'Mongolian Baiti': ['windows'],
  'MS Gothic': ['windows'],
  'MV Boli': ['windows'],
  'Nirmala UI': ['windows'],
  'Palatino Linotype': ['windows'],
  'Segoe MDL2 Assets': ['windows'],
  'Segoe Print': ['windows'],
  'Segoe Script': ['windows'],
  'Segoe Semibold': ['windows'],
  'Segoe UI': ['windows'],
  'Segoe UI Black': ['windows'],
  'Segoe UI Emoji': ['windows'],
  'Segoe UI Historic': ['windows'],
  'Segoe UI Light': ['windows'],
  'Segoe UI Semibold': ['windows'],
  'Segoe UI Semilight': ['windows'],
  'Segoe UI Symbol': ['windows'],
  'Segoe UI Variable': ['windows'],
  'SimSun': ['windows'],
  'Sitka Banner': ['windows'],
  'Sitka Display': ['windows'],
  'Sitka Heading': ['windows'],
  'Sitka Small': ['windows'],
  'Sitka Subheading': ['windows'],
  'Sitka Text': ['windows'],
  'Sylfaen': ['windows'],
  'Symbol': ['windows'],
  'Tahoma': ['windows'],
  'Times New Roman': ['windows'],
  'Trebuchet MS': ['windows'],
  'Verdana': ['windows'],
  'Yu Gothic': ['windows'],
  'Yu Gothic UI': ['windows'],
  // Web-safe (appear everywhere, lower signal)
  'Webdings': ['windows'],
  'Wingdings': ['windows'],

  // === macOS ===
  '.SF NS': ['macos'],
  '.SF NS Rounded': ['macos'],
  'Apple Braille': ['macos'],
  'Apple Chancery': ['macos'],
  'Apple Color Emoji': ['macos', 'windows'],
  'Apple SD Gothic Neo': ['macos'],
  'Apple Symbols': ['macos'],
  'AppleGothic': ['macos'],
  'AppleMyungjo': ['macos'],
  'Aqua Kana': ['macos'],
  'Arial Hebrew': ['macos', 'windows'],
  'Arial Rounded MT Bold': ['macos', 'windows'],
  'Avenir': ['macos'],
  'Avenir Next': ['macos'],
  'Avenir Next Condensed': ['macos'],
  'Baskerville': ['macos'],
  'Big Caslon': ['macos'],
  'Brush Script MT': ['macos'],
  'Chalkboard': ['macos'],
  'Chalkboard SE': ['macos'],
  'Chalkduster': ['macos'],
  'Cochin': ['macos'],
  'Copperplate': ['macos'],
  'Corsiva Hebrew': ['macos'],
  'Courier': ['macos'],
  'DIN Alternate': ['macos'],
  'DIN Condensed': ['macos'],
  'Futura': ['macos'],
  'Geneva': ['macos'],
  'Georgia': ['macos'],
  'Gill Sans': ['macos'],
  'Hannotate SC': ['macos'],
  'Hannotate TC': ['macos'],
  'Hiragino Kaku Gothic Pro': ['macos'],
  'Hiragino Kaku Gothic ProN': ['macos'],
  'Hiragino Maru Gothic Pro': ['macos'],
  'Hiragino Maru Gothic ProN': ['macos'],
  'Hiragino Mincho ProN': ['macos'],
  'Hiragino Sans': ['macos'],
  'Hiragino Sans GB': ['macos'],
  'Helvetica': ['macos'],
  'Helvetica Neue': ['macos'],
  'Hiragino Sans GB': ['macos'],
  'Hoefler Text': ['macos'],
  'Iowan Old Style': ['macos'],
  'Kefa': ['macos'],
  'Khmer Sangam MN': ['macos'],
  'Kohinoor Bangla': ['macos'],
  'Kohinoor Devanagari': ['macos'],
  'Kohinoor Telugu': ['macos'],
  'Lao Sangam MN': ['macos'],
  'Luminari': ['macos'],
  'Marian': ['macos'],
  'Marker Felt': ['macos'],
  'Menlo': ['macos'],
  'Monaco': ['macos'],
  'Noteworthy': ['macos'],
  'Noto Sans': ['macos', 'linux'],
  'Noto Sans CJK SC': ['macos', 'linux'],
  'Noto Sans CJK TC': ['macos', 'linux'],
  'Optima': ['macos'],
  'Palatino': ['macos'],
  'Papyrus': ['macos'],
  'Phosphate': ['macos'],
  'PingFang HK': ['macos'],
  'PingFang SC': ['macos'],
  'PingFang TC': ['macos'],
  'Raleway': ['macos'],
  'Rockwell': ['macos'],
  'Savoye LET': ['macos'],
  'SF Compact': ['macos'],
  'SF Compact Rounded': ['macos'],
  'SF Mono': ['macos'],
  'SF Pro': ['macos'],
  'SF Pro Display': ['macos'],
  'SF Pro Rounded': ['macos'],
  'SF Pro Text': ['macos'],
  'Skia': ['macos'],
  'Snell Roundhand': ['macos'],
  'Songti SC': ['macos'],
  'Songti TC': ['macos'],
  'STHeiti': ['macos'],
  'STIXGeneral': ['macos'],
  'STIXIntegralsD': ['macos'],
  'STIXIntegralsSm': ['macos'],
  'STIXIntegralsUp': ['macos'],
  'STIXIntegralsUpD': ['macos'],
  'STIXIntegralsUpSm': ['macos'],
  'SThai': ['macos'],
  'Symbol': ['macos'],
  'Thonburi': ['macos'],
  'Times': ['macos'],
  'Times New Roman': ['macos'],
  'Trebuchet MS': ['macos'],
  'Verdana': ['macos'],
  'Waseem': ['macos'],
  'Zapf Dingbats': ['macos'],
  'Zapfino': ['macos'],

  // === LINUX (Ubuntu/Debian/Fedora common) ===
  'AR PL UMing CN': ['linux'],
  'AR PL UKai CN': ['linux'],
  'Bitstream Charter': ['linux'],
  'Bitstream Vera Sans': ['linux'],
  'Bitstream Vera Sans Mono': ['linux'],
  'Bitstream Vera Serif': ['linux'],
  'Cantarell': ['linux'],
  'Courier 10 Pitch': ['linux'],
  'DejaVu Sans': ['linux'],
  'DejaVu Sans Mono': ['linux'],
  'DejaVu Serif': ['linux'],
  'Droid Sans': ['linux'],
  'Droid Sans Fallback': ['linux'],
  'Droid Sans Mono': ['linux'],
  'Droid Serif': ['linux'],
  'Fira Code': ['linux'],
  'Fira Mono': ['linux'],
  'Fira Sans': ['linux'],
  'FreeMono': ['linux'],
  'FreeSans': ['linux'],
  'FreeSerif': ['linux'],
  'Garuda': ['linux'],
  'Gentium Plus': ['linux'],
  'Georgia': ['linux'],
  'GURU NANAK': ['linux'],
  'Liberation Mono': ['linux'],
  'Liberation Sans': ['linux'],
  'Liberation Serif': ['linux'],
  'LKLUG': ['linux'],
  'Lohit Bengali': ['linux'],
  'Lohit Devanagari': ['linux'],
  'Lohit Tamil': ['linux'],
  'Lohit Telugu': ['linux'],
  'Meera Inimai': ['linux'],
  'Monospace': ['linux'],
  'NanumGothic': ['linux'],
  'NanumMyeongjo': ['linux'],
  'Nimbus Mono PS': ['linux'],
  'Nimbus Roman No9 L': ['linux'],
  'Nimbus Sans L': ['linux'],
  'Noto Color Emoji': ['linux'],
  'Noto Mono': ['linux'],
  'Noto Sans': ['linux'],
  'Noto Sans Armenian': ['linux'],
  'Noto Sans Bengali': ['linux'],
  'Noto Sans CJK JP': ['linux'],
  'Noto Sans CJK KR': ['linux'],
  'Noto Sans CJK SC': ['linux'],
  'Noto Sans CJK TC': ['linux'],
  'Noto Sans Devanagari': ['linux'],
  'Noto Sans Emoji': ['linux'],
  'Noto Sans Georgian': ['linux'],
  'Noto Sans Gujarati': ['linux'],
  'Noto Sans Kannada': ['linux'],
  'Noto Sans Malayalam': ['linux'],
  'Noto Sans Oriya': ['linux'],
  'Noto Sans Tamil': ['linux'],
  'Noto Sans Telugu': ['linux'],
  'Noto Sans Thai': ['linux'],
  'Noto Serif': ['linux'],
  'Noto Serif CJK JP': ['linux'],
  'Noto Serif CJK KR': ['linux'],
  'Noto Serif CJK SC': ['linux'],
  'Noto Serif CJK TC': ['linux'],
  'Noto Serif Devanagari': ['linux'],
  'Open Sans': ['linux'],
  'Padauk': ['linux'],
  'PT Mono': ['linux'],
  'PT Sans': ['linux'],
  'PT Serif': ['linux'],
  'Purisa': ['linux'],
  'Rachana': ['linux'],
  'Roboto': ['linux'],
  'Roboto Mono': ['linux'],
  'Sawasdee': ['linux'],
  'Scheherazade New': ['linux'],
  'Standard Symbols PS': ['linux'],
  'Symbola': ['linux'],
  'TakaoGothic': ['linux'],
  'TakaoPGothic': ['linux'],
  'Tahoma': ['linux'],
  'Tharlon': ['linux'],
  'Tibetan Machine Uni': ['linux'],
  'Times New Roman': ['linux'],
  'Tlwg Mono': ['linux'],
  'Tlwg Typist': ['linux'],
  'Tlwg Typo': ['linux'],
  'Ubuntu': ['linux'],
  'Ubuntu Bold': ['linux'],
  'Ubuntu Condensed': ['linux'],
  'Ubuntu Light': ['linux'],
  'Ubuntu Mono': ['linux'],
  'Ubuntu Thin': ['linux'],
  'Umpush': ['linux'],
  'UnBatang': ['linux'],
  'UnDotsuru': ['linux'],
  'UnGraphic': ['linux'],
  'UnGungseo': ['linux'],
  'Untitled1': ['linux'],
  'Utopia': ['linux'],
  'Vera Sans': ['linux'],
  'Vera Sans Mono': ['linux'],
  'Vera Serif': ['linux'],
  'Verdana': ['linux'],
  'Waree': ['linux'],
  'WenQuanYi Micro Hei': ['linux'],
  'WenQuanYi Zen Hei': ['linux'],
};

/** Get fonts for a given OS, optionally with some randomization */
function getFontsForOS(os, rng) {
  const fonts = Object.entries(FONT_DATABASE)
    .filter(([, osList]) => osList.includes(os))
    .map(([name]) => name);

  // Add ~10-20% random extra fonts from other OS (users may have installed them)
  const otherFonts = Object.entries(FONT_DATABASE)
    .filter(([, osList]) => !osList.includes(os))
    .map(([name]) => name);
  const extraCount = Math.floor(otherFonts.length * (0.08 + rng.next() * 0.12));
  const extras = rng.shuffle(otherFonts).slice(0, extraCount);

  return rng.shuffle([...fonts, ...extras]);
}

if (typeof globalThis !== 'undefined') {
  globalThis.FONT_DATABASE = FONT_DATABASE;
  globalThis.getFontsForOS = getFontsForOS;
}
