/**
 * OS-consistent GPU (WebGL renderer) database.
 * Each entry defines vendor, renderer, and a realistic extension set.
 * ANGLE prefix is stripped for unmasked values.
 */

const GPU_DATABASE = {
  windows: [
    {
      vendor: 'Google Inc. (NVIDIA)',
      renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 Ti SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)',
      unmaskedVendor: 'NVIDIA Corporation',
      unmaskedRenderer: 'NVIDIA GeForce RTX 4070 Ti SUPER',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_compression_bzip2', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context', 'WEBGL_multi_draw'],
      maxTextureSize: 32768,
      maxRenderBufferSize: 32768,
      maxViewportDims: [32768, 32768],
      maxCubeMapSize: 32768,
      pointSizeRange: [1, 2048],
      hardwareConcurrency: [12, 16, 20, 24],
      deviceMemory: [8, 12, 16],
    },
    {
      vendor: 'Google Inc. (NVIDIA)',
      renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)',
      unmaskedVendor: 'NVIDIA Corporation',
      unmaskedRenderer: 'NVIDIA GeForce RTX 3060',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_compression_bzip2', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context', 'WEBGL_multi_draw'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 2048],
      hardwareConcurrency: [8, 12, 16],
      deviceMemory: [8, 12],
    },
    {
      vendor: 'Google Inc. (NVIDIA)',
      renderer: 'ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)',
      unmaskedVendor: 'NVIDIA Corporation',
      unmaskedRenderer: 'NVIDIA GeForce GTX 1660 SUPER',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 1024],
      hardwareConcurrency: [6, 8],
      deviceMemory: [8, 16],
    },
    {
      vendor: 'Google Inc. (AMD)',
      renderer: 'ANGLE (AMD, AMD Radeon RX 6700 XT Direct3D11 vs_5_0 ps_5_0, D3D11)',
      unmaskedVendor: 'ATI Technologies Inc.',
      unmaskedRenderer: 'AMD Radeon RX 6700 XT',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_compression_bzip2', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 1024],
      hardwareConcurrency: [8, 12, 16],
      deviceMemory: [8, 16],
    },
    {
      vendor: 'Google Inc. (Intel)',
      renderer: 'ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)',
      unmaskedVendor: 'Intel',
      unmaskedRenderer: 'Intel(R) UHD Graphics 630',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 256],
      hardwareConcurrency: [4, 8],
      deviceMemory: [8],
    },
    {
      vendor: 'Google Inc. (Intel)',
      renderer: 'ANGLE (Intel, Intel(R) Arc(TM) A770 Direct3D11 vs_5_0 ps_5_0, D3D11)',
      unmaskedVendor: 'Intel',
      unmaskedRenderer: 'Intel(R) Arc(TM) A770',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_compression_bzip2', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context', 'WEBGL_multi_draw'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 1024],
      hardwareConcurrency: [8, 12, 16],
      deviceMemory: [8, 16],
    },
  ],
  macos: [
    {
      vendor: 'Google Inc. (Apple)',
      renderer: 'ANGLE (Apple, Apple M3, OpenGL 4.1)',
      unmaskedVendor: 'Apple',
      unmaskedRenderer: 'Apple M3',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 1024],
      hardwareConcurrency: [8, 10, 12],
      deviceMemory: [8, 16, 24, 36],
    },
    {
      vendor: 'Google Inc. (Apple)',
      renderer: 'ANGLE (Apple, Apple M2 Pro, OpenGL 4.1)',
      unmaskedVendor: 'Apple',
      unmaskedRenderer: 'Apple M2 Pro',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 1024],
      hardwareConcurrency: [10, 12],
      deviceMemory: [16, 32],
    },
    {
      vendor: 'Google Inc. (Apple)',
      renderer: 'ANGLE (Apple, Apple M1, OpenGL 4.1)',
      unmaskedVendor: 'Apple',
      unmaskedRenderer: 'Apple M1',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 1024],
      hardwareConcurrency: [8],
      deviceMemory: [8, 16],
    },
  ],
  linux: [
    {
      vendor: 'Mesa/X.org',
      renderer: 'Mesa Intel(R) UHD Graphics 770 (ADL-S GT2)',
      unmaskedVendor: 'Intel Open Source Technology Center',
      unmaskedRenderer: 'Mesa Intel(R) UHD Graphics 770 (ADL-S GT2)',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_compression_bzip2', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 1024],
      hardwareConcurrency: [8, 12, 16],
      deviceMemory: [8, 16, 32],
    },
    {
      vendor: 'Mesa/X.org',
      renderer: 'Mesa AMD RADV NAVI22 (ACO)',
      unmaskedVendor: 'X.Org',
      unmaskedRenderer: 'AMD Radeon RX 6800 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.8.0-45-generic)',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_compression_bzip2', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context'],
      maxTextureSize: 16384,
      maxRenderBufferSize: 16384,
      maxViewportDims: [16384, 16384],
      maxCubeMapSize: 16384,
      pointSizeRange: [1, 1024],
      hardwareConcurrency: [8, 12, 16],
      deviceMemory: [8, 16, 32],
    },
    {
      vendor: 'X.Org',
      renderer: 'NVIDIA Corporation NVIDIA GeForce RTX 4060/PCIe/SSE2',
      unmaskedVendor: 'NVIDIA Corporation',
      unmaskedRenderer: 'NVIDIA GeForce RTX 4060/PCIe/SSE2',
      extensions: ['ANGLE_instanced_arrays', 'EXT_blend_minmax', 'EXT_color_buffer_half_float', 'EXT_float_blend', 'EXT_frag_depth', 'EXT_shader_texture_lod', 'EXT_texture_compression_bzip2', 'EXT_texture_filter_anisotropic', 'EXT_sRGB', 'OES_element_index_uint', 'OES_fbo_render_mipmap', 'OES_standard_derivatives', 'OES_texture_float', 'OES_texture_float_linear', 'OES_texture_half_float', 'OES_texture_half_float_linear', 'OES_vertex_array_object', 'WEBGL_color_buffer_float', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb', 'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_depth_texture', 'WEBGL_draw_buffers', 'WEBGL_lose_context', 'WEBGL_multi_draw'],
      maxTextureSize: 32768,
      maxRenderBufferSize: 32768,
      maxViewportDims: [32768, 32768],
      maxCubeMapSize: 32768,
      pointSizeRange: [1, 2048],
      hardwareConcurrency: [8, 12, 16],
      deviceMemory: [8, 16, 32],
    },
  ],
};

if (typeof globalThis !== 'undefined') {
  globalThis.GPU_DATABASE = GPU_DATABASE;
}
